#!/usr/bin/env ansible-playbook
---
- name: Setting passwordless sudo for core user
  lineinfile:
    path: /etc/sudoers.d/waagent
    regexp: '/core'
    line: 'core ALL=(ALL) NOPASSWD: ALL'
  sudo: true

-
